name: Java CI with Maven

on:
  push:
    branches: [ master ]
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout master branch from Github
      - uses: actions/checkout@v2
      
      - name: Set up JDK 1.8
      - uses: actions/setup-java@v1
      - with:
          java-version: '1.8'
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: List the current directory
        run: ls -a
        
      - name: Finding the target folder
        run: 
          cd target
          ls -a
